### ISSUE TITLE
Roam can't connect to GPS in Windows 10

### ISSUE THREAD

**Issue by JuanPufleau** [roam-qgis/Roam#431]
Hi.   We are having problems with Roam, we can't connect to the GPS in Windows 10.   We can do it from a different tablet with Windows 7, and from several other GPS applications on the Windows 10 tablet, but not from Roam.

Does anybody know how to solve this?

I've attached a file with a detailed description of what we've tested.

Thanks in advance.
[IntraMaps Roam GPS issues on Windows 10.docx](https://github.com/roam-qgis/Roam/files/3006138/IntraMaps.Roam.GPS.issues.on.Windows.10.docx)

**Comment by JuanPufleau** [comment]
We have found that the problem is affecting Roam, but might be inheriting it from QGIS on those tablet computers.  When you open QGIS 2.18 on that tablet, and use View / Panels / GPS Information Panel, QGIS is not able to read the GPS in Com5, and the error messages takes approx 1 sec to show for Com5, and roughly 10 secs for other ports.  And the 'scan' option takes a little over 10 secs per Com port, not including Com5.

**Comment by JuanPufleau** [comment]
We've just tested that MapInfo Pro can also communicate via Com5 on that device to get the GPS reading properly.   

So, the list of applications we've tested successfully is:
- MapInfo Pro. 
- Dell Rugged Control Centre.
- Dell U-Centre
- GPS NMEA Monitor
- Dell GPS Direct (GPS Sensor)
- IntraMaps Enterprise

And the only 2 applications that don't work are:
- QGIS 2.18
- IntraMaps Roam

**Comment by JuanPufleau** [comment]
Well, after some investigation, I've been able to find out that:

+ Roam uses the QgsGPSDetector command to try a connection to the gps.  From the Roam source file gps.py

+ The QgsGPSDetector command in Qgis tries to use the gps daemon gpsd to try a connection, before going out to the Com ports.  And it uses the localhost:2947:  TCP port to do it.  From the QGIS API Documentation.

+ And one of the pieces of software that do work in Com for that tablet has the ability to broadcast NMEA commands via gpsd.  The GPS NMEA Monitor from http://4river.a.la9.jp/gps/

So, after configuring this GPS NMEA Monitor to output the gps info on gpsd, Qgis was able to detect the gps when configuring  View / Panels / GPS Information Panel, and also Roam did it, when the gps is set to scan all ports.  This software needs to run permanently in the background, but now we have a workaround for this problem.

**Comment by bwragg** [comment]
I had similar issues with ROAM. Seemed to be something in the GPS string messing it up. We ended up buying/installing a program called GPSGate  for around $20USD from memory (I am not affiliated in any way). It  takes the input string, cleans it up and spits out a nice clean string. Zero problems after that.

**Comment by Kostassan** [comment]
Hello, ts seems I have the same issue. Could you provide a more detailed explanation of how you did the configuration in GPs NMEA Monitor?

**Comment by JuanPufleau** [comment]
To complete the picture, I've tested QGIS 3.4.   It works with no problems.  

However, this is not yet an option for Roam, since we know are are still far from Roam 3.

**Comment by JuanPufleau** [comment]
> Hello, ts seems I have the same issue. Could you provide a more detailed explanation of how you did the configuration in GPs NMEA Monitor?

Kostassan, you just have to configure the correct Com port as input, enable the gps daemon (gpsd) output to localhost on the port mentioned above, and ensure the application is always running in the background.

**Comment by Kostassan** [comment]
JuanPufleau thank you. I just rolled back the drivers of the device's GNSS receiver and now in works OK
