### ISSUE TITLE
GPS not active

### ISSUE THREAD

**Issue by Kostassan** [roam-qgis/Roam#433]
Hello
I have been using the app with success in several tablets. However, I recently installed it ina Juniper Mesa 2 and the GPS in Roam does not seem to be working even when I switch the post to the same pot where the GNSS receivers located. (port 4, according to the tablets own GPS software) Also in the device manager, the GNSS receiver has a location of Port_#001.hub.#002. Have tried with both latest release of Roam. 2.7 and older ones. 
Any suggestions?

**Comment by rjwillson** [comment]
I have been using Roam on 4 different Mesa 2s for the last year on default com 4 port. I wonder if you have a more recent or older firmware on the Mesa that has changed the NMEA string format

**Comment by Kostassan** [comment]
This is new out of the box Mesa 2 and I have upgraded firmware and install a recent patch but still the same problem.

**Comment by Kostassan** [comment]
I rolled back the drivers of the GNSS receiver and it defaulted on COM3 and it works!
