### ISSUE TITLE
DIgitise not storing Geometry

### ISSUE THREAD

**Issue by blacknell84** [roam-qgis/Roam#437]
Been trying to get this working, but seem to be struggling

Using 2.71 with QGIS 2.18.22

I have set up a project with spatialite db and also separately with shapefiles and whenever I use a form to create a new point/line/polygon no geometry is stored - I cannot see the new entry in Roam or in QGIS. I can see the entry on the attribute table but nothing appears to be being stored for geometry.

Is this still a working project or am I looking at something that no longer works?

**Comment by rjwillson** [comment]
Sounds like your data collection layers are not in the same coordinate reference system (CRS) as the project. This is a requirement of Roam. Your other layers not used for data collection can have different CRSs.

Do a save as (export) and set the CRS of the shapefile or SQLite. Then make sure your Q project is set to that CRS. Should work

**Comment by blacknell84** [comment]
Worked like a charm, thanks


Now to work out how to get this working on an apache server :)
