### ISSUE TITLE
Question: Roam with 3D Model (Cesium B3dm)

### ISSUE THREAD

**Issue by lydonchandra** [roam-qgis/Roam#439]
Any plan to support 3d models ?
(Does QGIS plan to support 3d models ?)
using CesiumJs & B3dm for our 3d models 

need this for oil rig inspections, for example ^_^

https://sketchfab.com/3d-models/offshore-oil-rig-308891687ef44238b6b97bb618fcc720

![image](https://user-images.githubusercontent.com/158145/62757123-ca23dd00-baac-11e9-9d2c-c209b0759780.png)

[3DTilesInAction.pdf](https://github.com/roam-qgis/Roam/files/3484938/3DTilesInAction.pdf)

**Comment by NathanW2** [comment]
Hello @lydonchandra long time no see ;P

No plans currently. Once on QGIS 3 it might be possible but no solid plans yet.

**Comment by mgiana** [comment]
Hi @lydonchandra interesting idea. Would that to be just add attribute data or do geometry as well?

**Comment by stephdms** [comment]
good try @lydonchandra, ask @NathanW2 to do your job :)

**Comment by lydonchandra** [comment]
@mgiana initially will be attribute data, eventually will need to add to 3d mesh/vertices. 
Similar to IntraMaps DataEntry Edit Feature, but for 3D.

**Comment by lydonchandra** [comment]
@NathanW2  Roam wouldn't work with QtWebEngine to render the "3d-layer", would it ?
The inspection forms are then handled by Roam natively.
Similar to IntraMaps-qgis-plugin, but with forms handled by Roam ?

Or does it not work like that at all ? 😸

**Comment by NathanW2** [comment]
@lydonchandra  the webkit that ships with Roam (QGIS 2.18) is pretty junk for that kind of thing.  The update to QGIS 3 should help.

**Comment by rslevin-fmg** [comment]
Hi - Just touching base on this again, Any future scope to add 3D? Not so much OBJ models, but incorporating DEM'S for elevation
