### ISSUE TITLE
Could not find qGIS in Config Manager

### ISSUE THREAD

**Issue by janekska** [roam-qgis/Roam#444]
Hi,

I would like to test Roam.3.0.2-beta-2

I can create a test project in config manager, but stuck in config of it:

When pushing button ""Open project in qGIS" I am getting error:

> Can't find installed QGIS in: ['C:\\Program Files\\QGIS 3.4\\bin\\qgis-ltr-bin.exe', 'C:\\Program Files (x86)\\QGIS 3.4\\bin\\qgis-ltr-bin.exe']

When I looked in roam.config file there was wrong path:
configmanager:
  qgislocation: C:/OSGeo4W/bin/qgis.bat

I corrected it (in my case C:/OSGeo4W64/bin/qgis.bat), but still the same error.
I can start qGIS by the bat file above, but in my case it is qGIS 3.8.

There also errors when I am trying to "Add layers in qGIS":
> Something has gone wrong.
> Error: AttributeError: 'ProjectInfoWidget' object has no attribute 'bar'
> Traceback (most recent call last):
>   File "C:\Users\Nathan\dev\Roam\src\configmanager\ui\layerwidgets.py", line 871, in open_qgis
>   File "C:\Users\Nathan\dev\Roam\src\configmanager\utils.py", line 43, in openqgis
>   File "C:\Users\Nathan\dev\Roam\src\configmanager\utils.py", line 34, in find_qgis
> configmanager.utils.QGISNotFound: ['C:\\Program Files\\QGIS 3.4\\bin\\qgis-ltr-bin.exe', 'C:\\Program Files (x86)\\QGIS 3.4\\bin\\qgis-ltr-bin.exe']
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\Nathan\dev\Roam\src\configmanager\ui\layerwidgets.py", line 873, in open_qgis
> AttributeError: 'ProjectInfoWidget' object has no attribute 'bar'

It looks like it is something wrong with path.
Is it fixable by some config changes or should I use exact QGIS 3.4 version in the path shown in error messages?

**Comment by NathanW2** [comment]
Roam now looks for QGIS 3.10 installed via the standalone installers.  Configmanager needs QGIS 3.10 as that is going to be the next LTR.

**Comment by HeatherHillers** [comment]
Now that the 3.10 is the LTR, can we add C:\OSGeo4W64\bin to the search path for qgis?
