### ISSUE TITLE
Dropdown list from layer not working

### ISSUE THREAD

**Issue by amatter** [roam-qgis/Roam#459]
I just tried to update an older project to roam 3 beta 3.

when using list from layer in roam, clicking the list does do nothing, presents not the expected list.

![20200402_roam3b3_dropdown-list](https://user-images.githubusercontent.com/3266376/78243796-b0745180-74e4-11ea-9188-9340276cfa78.png)

**Comment by she-weeds** [comment]
I wasn't able to reproduce this. Did the exact same project work in beta 2?

How about if you had a list for a string values (for both the value column in the list, and the field itself)

**Comment by amatter** [comment]
Hi,
I guess yes (but do not remember 100%)  when I was testing the rotation  (#425).
Actually I do not understand the 2nd sentence "How about ... ". can you please give a short example what you like me to try.
Thanks

**Comment by she-weeds** [comment]
You have an integer field as the underlying data in the list (and field type) and a text field as the description - reasonable to expect this to work especially of it has in the past. Maybe see if it works if everything was text/string? If it does that helps narrow down the issues for the devs

**Comment by amatter** [comment]
Found a solution in ROAM 3.0.6. just add a filter over the attributes like :   "grund_code"  ||  ' '  ||  "grund_txt"

**Comment by amatter** [comment]
see above
